// <auto-generated />
using System;
using FitCalorie.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitCalorie.Migrations
{
    [DbContext(typeof(FoodContext))]
    [Migration("20260827103630_seemorefood")]
    partial class seemorefood
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitCalorie.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalCalorie")
                        .HasColumnType("float");

                    b.Property<double>("TotalCarb")
                        .HasColumnType("float");

                    b.Property<double>("TotalFat")
                        .HasColumnType("float");

                    b.Property<double>("TotalProtein")
                        .HasColumnType("float");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FitCalorie.Models.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AmountGrames")
                        .HasColumnType("float");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId");

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("FitCalorie.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("calorie")
                        .HasColumnType("float");

                    b.Property<double>("carb")
                        .HasColumnType("float");

                    b.Property<double>("fat")
                        .HasColumnType("float");

                    b.Property<double>("protein")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Grilled Chicken Breast",
                            calorie = 165.0,
                            carb = 0.0,
                            fat = 3.6000000000000001,
                            protein = 31.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Boiled Egg",
                            calorie = 155.0,
                            carb = 1.1000000000000001,
                            fat = 11.0,
                            protein = 13.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Egg Whites",
                            calorie = 52.0,
                            carb = 0.69999999999999996,
                            fat = 0.20000000000000001,
                            protein = 11.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Canned Tuna in Water",
                            calorie = 116.0,
                            carb = 0.0,
                            fat = 1.0,
                            protein = 26.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Grilled Salmon",
                            calorie = 206.0,
                            carb = 0.0,
                            fat = 12.0,
                            protein = 22.0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Lean Ground Beef (90/10)",
                            calorie = 215.0,
                            carb = 0.0,
                            fat = 12.0,
                            protein = 26.0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cottage Cheese (Low Fat)",
                            calorie = 72.0,
                            carb = 2.7000000000000002,
                            fat = 1.0,
                            protein = 12.4
                        },
                        new
                        {
                            Id = 8,
                            Name = "Greek Yogurt (0% Fat)",
                            calorie = 59.0,
                            carb = 3.6000000000000001,
                            fat = 0.40000000000000002,
                            protein = 10.0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Whey Protein Powder",
                            calorie = 380.0,
                            carb = 6.0,
                            fat = 3.5,
                            protein = 80.0
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tofu (Firm)",
                            calorie = 76.0,
                            carb = 1.8999999999999999,
                            fat = 4.7999999999999998,
                            protein = 8.0
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cooked White Rice",
                            calorie = 130.0,
                            carb = 28.199999999999999,
                            fat = 0.29999999999999999,
                            protein = 2.7000000000000002
                        },
                        new
                        {
                            Id = 12,
                            Name = "Cooked Brown Rice",
                            calorie = 112.0,
                            carb = 23.5,
                            fat = 0.90000000000000002,
                            protein = 2.6000000000000001
                        },
                        new
                        {
                            Id = 13,
                            Name = "Raw Oats",
                            calorie = 389.0,
                            carb = 66.299999999999997,
                            fat = 6.9000000000000004,
                            protein = 16.899999999999999
                        },
                        new
                        {
                            Id = 14,
                            Name = "Boiled Sweet Potato",
                            calorie = 86.0,
                            carb = 20.100000000000001,
                            fat = 0.10000000000000001,
                            protein = 1.6000000000000001
                        },
                        new
                        {
                            Id = 15,
                            Name = "Boiled White Potato",
                            calorie = 87.0,
                            carb = 20.100000000000001,
                            fat = 0.10000000000000001,
                            protein = 1.8999999999999999
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cooked Pasta (White)",
                            calorie = 158.0,
                            carb = 30.899999999999999,
                            fat = 0.90000000000000002,
                            protein = 5.7999999999999998
                        },
                        new
                        {
                            Id = 17,
                            Name = "Cooked Whole Wheat Pasta",
                            calorie = 124.0,
                            carb = 26.5,
                            fat = 0.5,
                            protein = 5.2999999999999998
                        },
                        new
                        {
                            Id = 18,
                            Name = "Cooked Lentils",
                            calorie = 116.0,
                            carb = 20.0,
                            fat = 0.40000000000000002,
                            protein = 9.0
                        },
                        new
                        {
                            Id = 19,
                            Name = "Cooked Chickpeas",
                            calorie = 164.0,
                            carb = 27.399999999999999,
                            fat = 2.6000000000000001,
                            protein = 8.9000000000000004
                        },
                        new
                        {
                            Id = 20,
                            Name = "Whole Wheat Bread (100g)",
                            calorie = 247.0,
                            carb = 41.0,
                            fat = 3.3999999999999999,
                            protein = 13.0
                        },
                        new
                        {
                            Id = 21,
                            Name = "Peanut Butter",
                            calorie = 588.0,
                            carb = 20.0,
                            fat = 50.0,
                            protein = 25.0
                        },
                        new
                        {
                            Id = 22,
                            Name = "Raw Almonds",
                            calorie = 579.0,
                            carb = 21.600000000000001,
                            fat = 49.899999999999999,
                            protein = 21.199999999999999
                        },
                        new
                        {
                            Id = 23,
                            Name = "Raw Walnuts",
                            calorie = 654.0,
                            carb = 13.699999999999999,
                            fat = 65.200000000000003,
                            protein = 15.199999999999999
                        },
                        new
                        {
                            Id = 24,
                            Name = "Fresh Avocado",
                            calorie = 160.0,
                            carb = 8.5,
                            fat = 14.699999999999999,
                            protein = 2.0
                        },
                        new
                        {
                            Id = 25,
                            Name = "Olive Oil",
                            calorie = 884.0,
                            carb = 0.0,
                            fat = 100.0,
                            protein = 0.0
                        },
                        new
                        {
                            Id = 26,
                            Name = "Banana",
                            calorie = 89.0,
                            carb = 22.800000000000001,
                            fat = 0.29999999999999999,
                            protein = 1.1000000000000001
                        },
                        new
                        {
                            Id = 27,
                            Name = "Apple",
                            calorie = 52.0,
                            carb = 13.800000000000001,
                            fat = 0.20000000000000001,
                            protein = 0.29999999999999999
                        },
                        new
                        {
                            Id = 28,
                            Name = "Fresh Strawberries",
                            calorie = 32.0,
                            carb = 7.7000000000000002,
                            fat = 0.29999999999999999,
                            protein = 0.69999999999999996
                        },
                        new
                        {
                            Id = 29,
                            Name = "Steamed Broccoli",
                            calorie = 35.0,
                            carb = 7.2000000000000002,
                            fat = 0.40000000000000002,
                            protein = 2.3999999999999999
                        },
                        new
                        {
                            Id = 30,
                            Name = "Raw Spinach",
                            calorie = 23.0,
                            carb = 3.6000000000000001,
                            fat = 0.40000000000000002,
                            protein = 2.8999999999999999
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FitCalorie.Models.DailyLog", b =>
                {
                    b.HasOne("FitCalorie.Models.FoodItem", "food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitCalorie.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("food");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FitCalorie.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FitCalorie.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCalorie.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FitCalorie.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
